name: renovate-config-validator

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.2.0
        with:
          pattern: '*.json'

